### ISSUE TITLE
Error on HTTP Plex instance

### ISSUE THREAD

**Issue by martadinata666** [diogonr/detsube#2]
My plex instance is on http side, and it throwing error invalid URL. On plex query.

```
cache miss 
2021-10-06 18:36:52.951  ERROR [src/core/decorators/catch.decorator.ts:7  defaultHandler] 
 TypeError  Invalid URL
details:
{
  input: '192.168.0.2:32400/hubs/search',
  code: 'ERR_INVALID_URL'
}
error stack:
• errors:371 NodeError
    node:internal/errors:371:5

• url:552 onParseError
    node:internal/url:552:9

• url:628 URL
    node:internal/url:628:5

• options-to-url.js:35 exports.default
    node_modules/got/dist/source/core/utils/options-to-url.js:35:17

• index.js:480 normalizeArguments
    node_modules/got/dist/source/core/index.js:480:51

• create.js:112 got
    node_modules/got/dist/source/create.js:112:39

• create.js:224 got.<computed>
    node_modules/got/dist/source/create.js:224:42

• http.client.ts:40 getJson
    src/core/services/http.client.ts:40:8

• plex.api.ts:30 search
    src/discord/modules/music/services/plex/plex.api.ts:30:38

• plex.service.ts:99 search
    src/discord/modules/music/services/plex/plex.service.ts:99:40

undefined 
2021-10-06 18:36:52.958  ERROR [process.<anonymous>] TypeError: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at Object.exports.default (/home/debian/discord/node_modules/got/dist/source/core/utils/options-to-url.js:35:17)
    at normalizeArguments (/home/debian/discord/node_modules/got/dist/source/core/index.js:480:51)
    at got (/home/debian/discord/node_modules/got/dist/source/create.js:112:39)
    at Function.got.<computed> [as get] (/home/debian/discord/node_modules/got/dist/source/create.js:224:42)
    at HttpClient.getJson (/home/debian/discord/src/core/services/http.client.ts:40:8)
    at PlexAPI.search (/home/debian/discord/src/discord/modules/music/services/plex/plex.api.ts:30:38)
    at PlexService.search (/home/debian/discord/src/discord/modules/music/services/plex/plex.service.ts:99:40) 
[ERROR] 01:36:52 TypeError: Invalid URL

```

config.ts
```
.....
plex: {
      hostname: '192.168.0.2',
      port: 32400,
      token: 'c2Y_zwv3qVEqRLVrTs-C',
      defaults: {
        limit: '15',
        includeCollections: '1',
        includeExternalMedia: "1",
        'X-Plex-Features': 'external-media%2Cindirect-media'
      },
....
```
If i set hostname to `http://192.168.0.2` the query work, but cant playback

**Comment by diogonr** [comment]
mine is set to http and it works
```ts
    plex: {
      hostname: 'http://192.168.31.181',
      port: 32400,
```

do you have ffmpeg installed in your machine?

**Comment by diogonr** [comment]
I created a discord server for support, if you need more help finding the issue
https://discord.gg/6Pjf5DgkvV

**Comment by diogonr** [comment]
Oh, I see it, thank you
I'll make lastfm optionally
